# Generated by Django 4.1.5 on 2023-01-12 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="PropertyDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("property_name", models.CharField(max_length=128)),
                ("address", models.CharField(max_length=256)),
                ("city", models.CharField(max_length=128)),
                ("state", models.CharField(max_length=128)),
            ],
        ),
    ]
